build: camera.cpp camera.h display.h display.cpp entity.cpp entity.h framebuffer.cpp framebuffer.h input.cpp input.h main.cpp mesh.cpp mesh.h  shader.cpp shader.h texture.cpp texture.h
	g++ *.cpp -lSDL2 -lGLEW -lGLU -lGL -o watersim -std=c++11
run:
	./watersim
