build: camera.cpp camera.h display.h display.cpp entity.cpp entity.h input.cpp input.h main.cpp mesh.cpp mesh.h  shader.cpp shader.h texture.cpp texture.h
	g++ -g *.cpp -lSDL2 -lGLEW -lGLU -lGL -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath -I/usr/include/bullet -o world2 -std=c++11
run:
	./world2
